export type KnowledgeCategory = 'academy' | 'starting' | 'technique' | 'progress' | 'safety' | 'parents' | 'adults' | 'preparation' | 'fitness' | 'communication';

export interface KnowledgeArticle {
  readonly id: string;
  readonly category: KnowledgeCategory;
  readonly keywordsAr: readonly string[];
  readonly keywordsEn: readonly string[];
  readonly answerAr: string;
  readonly answerEn: string;
  readonly core?: boolean;
}

export const ACADEMY_KNOWLEDGE: readonly KnowledgeArticle[] = [
  { id:'academy-overview', category:'academy', core:true, keywordsAr:['الاكاديمية','سويم فيت','swim fit','من انتم'], keywordsEn:['academy','swim fit','who are you','about'], answerAr:'سويم فيت أكاديمي تقدم تعليم سباحة لجميع المستويات في أبوظبي، مع تجربة رقمية ثنائية اللغة بالعربية والإنجليزية.', answerEn:'Swim Fit Academy provides swimming instruction for all levels in Abu Dhabi, with a bilingual Arabic and English digital experience.' },
  { id:'academy-levels', category:'academy', core:true, keywordsAr:['المستويات','كل المستويات','مبتدئ','متقدم'], keywordsEn:['levels','all levels','beginner','advanced'], answerAr:'المعلومة المؤكدة حاليًا أن الأكاديمية تخدم جميع المستويات. تحديد المستوى المناسب يبدأ بفهم خبرتك الحالية وهدفك في الماء.', answerEn:'The confirmed academy scope is all levels. The right starting point depends on your current water experience and your goal.' },
  { id:'academy-language', category:'academy', core:true, keywordsAr:['عربي','انجليزي','اللغة','لغة'], keywordsEn:['arabic','english','language','bilingual'], answerAr:'الموقع والمساعد يدعمان العربية والإنجليزية، ويمكنك الاستمرار باللغة التي تفضلها.', answerEn:'The website and assistant support Arabic and English, so you can continue in whichever language you prefer.' },
  { id:'academy-phone', category:'communication', core:true, keywordsAr:['رقم','هاتف','اتصال','تليفون'], keywordsEn:['phone','number','call','telephone'], answerAr:'رقم التواصل المؤكد هو 056 969 8628، وبالصيغة الدولية +971 56 969 8628.', answerEn:'The confirmed contact number is 056 969 8628, or +971 56 969 8628 internationally.' },
  { id:'academy-whatsapp', category:'communication', core:true, keywordsAr:['واتساب','واتس','راسل','تواصل'], keywordsEn:['whatsapp','message','text','contact'], answerAr:'يمكنك التواصل مباشرة عبر واتساب على الرقم +971 56 969 8628. التفاصيل المتغيرة مثل الأسعار والمواعيد والموقع الدقيق تحتاج تأكيد الإدارة.', answerEn:'You can contact the academy directly on WhatsApp at +971 56 969 8628. Variable details such as pricing, schedules, and exact venue need management confirmation.' },
  { id:'academy-facebook', category:'communication', keywordsAr:['فيسبوك','فيس بوك','صفحة'], keywordsEn:['facebook','social page'], answerAr:'يوجد رابط فيسبوك مدعوم ضمن بيانات الأكاديمية العامة. أي حساب اجتماعي آخر لا يُعرض كرسمي إلا بعد التحقق.', answerEn:'A supported Facebook page is part of the academy public data. Other social accounts are not presented as official until verified.' },
  { id:'first-time-swimmer', category:'starting', core:true, keywordsAr:['اول مرة','من الصفر','لا اعرف السباحة','مش بعرف اسبح'], keywordsEn:['first time','from scratch','never swam','cannot swim'], answerAr:'لو دي أول مرة، البداية الطبيعية تكون بالراحة في الماء، التحكم في التنفس، الطفو، وضع الجسم، ثم الحركة الأساسية. التقدم يكون خطوة بخطوة وليس بالقفز لمهارات صعبة.', answerEn:'For a first-time swimmer, a sensible path is water comfort, breathing control, floating, body position, then basic movement. Progress should be step by step rather than jumping into advanced skills.' },
  { id:'water-confidence', category:'starting', keywordsAr:['خوف','خايف','ثقة','توتر','رهبة الماء'], keywordsEn:['fear','afraid','confidence','nervous','water anxiety'], answerAr:'الخوف من الماء شائع، والأفضل التعامل معه تدريجيًا: دخول آمن، تنفس هادئ، تمارين قصيرة للوجه والطفو، ثم زيادة التحدي عند الشعور بالراحة.', answerEn:'Fear of water is common. A gradual approach works best: safe entry, calm breathing, short face-in-water and floating drills, then increasing difficulty only when comfortable.' },
  { id:'breathing-basics', category:'technique', keywordsAr:['تنفس','النفس','اخد نفس','زفير'], keywordsEn:['breathing','breath','exhale','inhale'], answerAr:'أساس التنفس في السباحة هو إخراج الهواء بهدوء داخل الماء وأخذ الشهيق بسرعة عند توفر الوضع المناسب، بدل حبس النفس لفترة طويلة.', answerEn:'A core swimming breathing habit is to exhale steadily in the water and take a quick inhale when the body position allows it, rather than holding your breath for too long.' },
  { id:'floating-basics', category:'starting', keywordsAr:['طفو','اعوم','افرد جسمي'], keywordsEn:['float','floating','stay up'], answerAr:'الطفو يعتمد على الاسترخاء ووضع الجسم والتنفس أكثر من القوة. شد الجسم أو رفع الرأس بقوة غالبًا يجعل الرجلين تهبطان.', answerEn:'Floating depends more on relaxation, body position, and breathing than strength. Tensing up or lifting the head aggressively often makes the legs sink.' },
  { id:'streamline', category:'technique', keywordsAr:['انسيابية','ستريم لاين','مقاومة الماء'], keywordsEn:['streamline','drag','water resistance'], answerAr:'الوضع الانسيابي يقلل مقاومة الماء: جسم ممتد، رأس بين الذراعين، وخط جسم طويل قدر الإمكان بعد الدفع.', answerEn:'A streamlined body reduces drag: long body line, head between the arms, and a compact shape after pushing off.' },
  { id:'freestyle', category:'technique', keywordsAr:['حرة','فري ستايل','كراول'], keywordsEn:['freestyle','front crawl','crawl'], answerAr:'في السباحة الحرة ركّز على وضع جسم مستقر، دوران بسيط للجذع، دخول يد نظيف، سحب فعال، وتنفس منتظم بدون رفع الرأس للأعلى.', answerEn:'For freestyle, focus on stable body position, controlled body rotation, clean hand entry, effective pull, and rhythmic breathing without lifting the head upward.' },
  { id:'backstroke', category:'technique', keywordsAr:['ظهر','باك ستروك'], keywordsEn:['backstroke','back stroke'], answerAr:'سباحة الظهر تحتاج وضع حوض مرتفع نسبيًا، رأس ثابت، ركلة مستمرة خفيفة، وتدوير متوازن للكتفين أثناء حركة الذراعين.', answerEn:'Backstroke benefits from a relatively high hip position, quiet head, light continuous kick, and balanced shoulder rotation through the arm cycle.' },
  { id:'breaststroke', category:'technique', keywordsAr:['صدر','براست ستروك'], keywordsEn:['breaststroke','breast stroke'], answerAr:'في سباحة الصدر التوقيت مهم: سحب، تنفس، ركلة، ثم انسياب. الاستعجال بين المراحل يقلل الكفاءة.', answerEn:'Breaststroke is highly timing-dependent: pull, breathe, kick, then glide. Rushing the sequence usually reduces efficiency.' },
  { id:'butterfly', category:'technique', keywordsAr:['فراشة','باترفلاي'], keywordsEn:['butterfly','fly stroke'], answerAr:'الفراشة مهارة متقدمة نسبيًا وتحتاج موجة جسم متصلة، ركلة دولفين متناسقة، وتوقيت واضح بين الذراعين والتنفس. الجودة أهم من عدد التكرارات.', answerEn:'Butterfly is relatively advanced and depends on connected body rhythm, coordinated dolphin kick, and clear timing between the arms and breathing. Quality matters more than repetition count.' },
  { id:'kick-efficiency', category:'technique', keywordsAr:['ركلة','رجلين','كيك'], keywordsEn:['kick','kicking','legs'], answerAr:'الركلة الفعالة تكون من الورك مع مرونة في الركبة والكاحل، وليس من ثني الركبة بقوة فقط. الرش الكبير لا يعني دائمًا دفعًا أفضل.', answerEn:'An efficient kick starts from the hip with relaxed knee and ankle action, not from aggressively bending the knees. Bigger splash does not always mean better propulsion.' },
  { id:'body-position', category:'technique', keywordsAr:['وضع الجسم','الجسم بيغرق','رجلي بتنزل'], keywordsEn:['body position','legs sink','hips sink'], answerAr:'وضع الجسم يتحسن عندما يكون الرأس هادئًا والجذع ثابتًا والتنفس منظمًا. رفع الرأس كثيرًا يدفع الحوض والرجلين لأسفل.', answerEn:'Body position improves when the head stays quiet, the core is controlled, and breathing is organized. Lifting the head too much tends to push the hips and legs down.' },
  { id:'stroke-efficiency', category:'technique', keywordsAr:['كفاءة','اقل مجهود','اتعب بسرعة'], keywordsEn:['efficiency','less effort','tire quickly'], answerAr:'الكفاءة تأتي من تقليل مقاومة الماء وتحسين التوقيت قبل محاولة زيادة القوة. سباحة أسرع لا تعني دائمًا تحريك الذراعين أسرع.', answerEn:'Efficiency comes from reducing drag and improving timing before adding more force. Swimming faster does not always mean moving the arms faster.' },
  { id:'turns-and-walls', category:'technique', keywordsAr:['لفة','الحائط','دوران','قلبة'], keywordsEn:['turn','wall','flip turn','push off'], answerAr:'التعامل الجيد مع الحائط يشمل الاقتراب المتزن، دوران مناسب للمستوى، دفع قوي في خط انسيابي، ثم عودة تدريجية للسباحة.', answerEn:'Good wall skills include a controlled approach, a turn appropriate to the swimmer level, a strong streamlined push-off, then a smooth return to swimming.' },
  { id:'progress-path', category:'progress', core:true, keywordsAr:['اتطور','تقدم','مراحل','مسار'], keywordsEn:['progress','improve','stages','path'], answerAr:'التقدم في السباحة عادة يبنى من الثقة والتحكم في الماء إلى التقنية، ثم الاتساق والتحمل والسرعة. تقييم التقدم يكون بجودة الحركة والاستقلال والثبات، وليس بالسرعة فقط.', answerEn:'Swimming progress usually builds from water confidence and control into technique, then consistency, endurance, and speed. Progress is measured by movement quality, independence, and repeatability, not speed alone.' },
  { id:'plateau', category:'progress', keywordsAr:['مش بتطور','ثابت','واقف مكاني','بلاتو'], keywordsEn:['plateau','not improving','stuck','no progress'], answerAr:'فترات الثبات طبيعية. الحل غالبًا يكون بتحديد مهارة واحدة قابلة للقياس، تقليل التعقيد، الحصول على ملاحظات، ثم تكرارها بجودة بدل تغيير كل شيء مرة واحدة.', answerEn:'Plateaus are normal. A useful response is to isolate one measurable skill, simplify the task, get feedback, and repeat it with quality instead of changing everything at once.' },
  { id:'practice-frequency', category:'progress', keywordsAr:['اتمرن كام مرة','عدد المرات','تكرار التدريب'], keywordsEn:['how often practice','frequency','times per week'], answerAr:'عدد الحصص المناسب يختلف حسب العمر والهدف والقدرة على الاستشفاء والجدول. المهم هو الانتظام وجودة التدريب؛ المواعيد الفعلية للأكاديمية تحتاج تأكيد الإدارة.', answerEn:'The right practice frequency varies with age, goals, recovery, and schedule. Consistency and quality matter most; the academy actual timetable needs management confirmation.' },
  { id:'goal-setting', category:'progress', keywordsAr:['هدفي','هدف','عايز اوصل'], keywordsEn:['goal','target','want to achieve'], answerAr:'أفضل هدف تدريبي يكون محددًا وقابلًا للملاحظة، مثل تحسين التنفس لمسافة قصيرة أو الحفاظ على وضع جسم أفضل، ثم الانتقال لهدف أصعب بعد ثبات المهارة.', answerEn:'A useful swimming goal is specific and observable, such as improving breathing over a short distance or holding a better body line, then progressing after the skill becomes consistent.' },
  { id:'children-learning', category:'parents', keywordsAr:['طفل','اطفال','ابني','بنتي'], keywordsEn:['child','children','kid','my son','my daughter'], answerAr:'تعلم الأطفال يكون أفضل عندما تكون الجلسة آمنة وإيجابية ومناسبة لقدرتهم على التركيز. الثقة والمهارات الأساسية تسبق الضغط على السرعة أو المسافات الطويلة.', answerEn:'Children learn best when sessions feel safe, positive, and appropriate to their attention span. Confidence and fundamentals come before pressure for speed or long distances.' },
  { id:'parent-support', category:'parents', keywordsAr:['ولي الامر','الاهل','اشجع ابني','اخلي طفلي يتعلم'], keywordsEn:['parent','support my child','help my kid'], answerAr:'أفضل دعم من ولي الأمر هو الهدوء والتشجيع وعدم مقارنة الطفل بغيره، مع الاهتمام بالانتظام والنوم والتجهيز للحصة أكثر من الضغط على النتيجة.', answerEn:'The best parent support is calm encouragement without comparing the child to others, while prioritizing consistency, sleep, and lesson preparation over pressure for results.' },
  { id:'child-fear', category:'parents', keywordsAr:['طفلي خايف','ابني خايف','بنتي خايفة'], keywordsEn:['child afraid','kid scared','my child fears water'], answerAr:'مع الطفل الخائف من الماء لا يُنصح بالإجبار أو المفاجأة. التدرج والاختيارات الصغيرة والنجاحات القصيرة تساعد على بناء الثقة بشكل أكثر استدامة.', answerEn:'For a child who fears water, forcing or surprising them is not a good approach. Gradual exposure, small choices, and short successes can build more durable confidence.' },
  { id:'adult-beginner', category:'adults', keywordsAr:['كبير','بالغ','عمري','اتعلم وانا كبير'], keywordsEn:['adult beginner','too old','learn as adult','my age'], answerAr:'تعلم السباحة للكبار ممكن، والبداية لا تحتاج خبرة سابقة. التدرج في التنفس والطفو ووضع الجسم يساعد على بناء أساس آمن قبل التركيز على السرعة.', answerEn:'Adults can learn to swim without prior experience. Gradual work on breathing, floating, and body position builds a safer foundation before focusing on speed.' },
  { id:'adult-fitness', category:'adults', keywordsAr:['لياقة','تخسيس','كارديو','رياضة'], keywordsEn:['fitness','cardio','exercise','weight loss'], answerAr:'السباحة يمكن أن تكون نشاطًا ممتازًا للياقة العامة لأنها تشغل مجموعات عضلية متعددة وتسمح بتدرج الشدة. أي هدف صحي أو علاجي محدد يحتاج توجيهًا طبيًا مناسبًا عند الحاجة.', answerEn:'Swimming can be excellent general fitness because it uses many muscle groups and allows intensity to scale. Specific medical or therapeutic goals should involve appropriate clinical guidance when needed.' },
  { id:'what-to-bring', category:'preparation', core:true, keywordsAr:['اجيب ايه','احضر ايه','شنطة','مستلزمات'], keywordsEn:['what to bring','pack','bag','equipment'], answerAr:'لجلسة سباحة عامة جهّز مايوه مناسب، منشفة، نظارة سباحة إن كانت مريحة لك، غطاء شعر عند الحاجة، مياه للشرب، وملابس جافة بعد التدريب.', answerEn:'For a general swim session, bring suitable swimwear, a towel, goggles if comfortable, a swim cap when useful, drinking water, and dry clothes for afterward.' },
  { id:'goggles', category:'preparation', keywordsAr:['نظارة','جوجلز','نضارة سباحة'], keywordsEn:['goggles','swim goggles'], answerAr:'النظارة الجيدة ينبغي أن تكون مريحة وتغلق حول العين بدون ضغط مبالغ. المقاس المناسب أهم من اختيار أغلى موديل.', answerEn:'Good goggles should feel comfortable and seal around the eyes without excessive pressure. Proper fit matters more than choosing the most expensive model.' },
  { id:'swim-cap', category:'preparation', keywordsAr:['كاب','غطاء الشعر','بونيه'], keywordsEn:['swim cap','cap'], answerAr:'غطاء السباحة يساعد على تثبيت الشعر وتقليل دخوله للوجه، وقد يكون مطلوبًا حسب سياسة المسبح. سياسة الموقع الفعلية تحتاج تأكيد الإدارة.', answerEn:'A swim cap helps keep hair controlled and away from the face, and some pools may require one. The actual venue policy needs management confirmation.' },
  { id:'hydration', category:'preparation', keywordsAr:['مياه','اشرب','ترطيب'], keywordsEn:['water','drink','hydration'], answerAr:'حتى في الماء يفقد الجسم سوائل، لذلك من المفيد الوصول مرطبًا وشرب الماء حسب الحاجة قبل وبعد التدريب.', answerEn:'You still lose fluid while swimming, so arriving hydrated and drinking water as needed before and after training is useful.' },
  { id:'arrival-prep', category:'preparation', keywordsAr:['اوصل امتى','قبل الحصة','استعداد'], keywordsEn:['arrive','before lesson','prepare'], answerAr:'بشكل عام من المفيد الوصول بوقت كافٍ لتغيير الملابس والاستعداد بهدوء بدل الدخول للحصة وأنت مستعجل. وقت الوصول المطلوب فعليًا يعتمد على الموقع وجدول الأكاديمية.', answerEn:'In general, arrive with enough time to change and settle in rather than rushing into the lesson. The exact arrival requirement depends on the venue and academy schedule.' },
  { id:'warmup', category:'fitness', keywordsAr:['احماء','تسخين','وارم اب'], keywordsEn:['warm up','warmup'], answerAr:'الإحماء الهادئ قبل الجهد يساعد الجسم على الانتقال تدريجيًا للعمل. يمكن أن يبدأ بحركة مفاصل بسيطة ثم سباحة سهلة قبل المجموعات الأصعب.', answerEn:'A gentle warm-up helps the body transition into harder work. It can begin with simple mobility and easy swimming before more demanding sets.' },
  { id:'endurance', category:'fitness', keywordsAr:['تحمل','نفس طويل','مسافة'], keywordsEn:['endurance','stamina','distance'], answerAr:'بناء التحمل يعتمد على الاستمرارية والإيقاع وتقنية اقتصادية أكثر من السباحة بأقصى سرعة من البداية. زد الحمل تدريجيًا مع الحفاظ على جودة الحركة.', answerEn:'Building endurance depends on consistency, pacing, and economical technique more than going all-out from the start. Increase load gradually while protecting movement quality.' },
  { id:'speed', category:'fitness', keywordsAr:['سرعة','اسرع','سريع'], keywordsEn:['speed','faster','sprint'], answerAr:'تحسين السرعة يبدأ غالبًا من انسيابية أفضل وتوقيت أقوى ثم إضافة القوة والسرعة. زيادة الجهد فوق تقنية غير مستقرة قد تزيد التعب أكثر من السرعة.', answerEn:'Speed often improves first through better streamlining and timing, then through added power. More effort on unstable technique can increase fatigue more than speed.' },
  { id:'recovery', category:'fitness', keywordsAr:['استشفاء','راحة','تعب','ارهاق'], keywordsEn:['recovery','rest','fatigue','tired'], answerAr:'الاستشفاء جزء من التدريب: نوم جيد، سوائل كافية، تغذية مناسبة، وأيام أخف عند الحاجة. الألم غير المعتاد أو المستمر يستحق تقييمًا متخصصًا.', answerEn:'Recovery is part of training: good sleep, hydration, appropriate nutrition, and lighter days when needed. Unusual or persistent pain deserves professional assessment.' },
  { id:'water-safety', category:'safety', core:true, keywordsAr:['سلامة','امان','غرق'], keywordsEn:['safety','safe','drowning','water safety'], answerAr:'السلامة في الماء أولوية: اتبع تعليمات المنقذ أو المدرب، لا تدخل عمقًا غير مناسب لقدرتك، ولا تعتمد على مهارة السباحة وحدها بدل الإشراف المناسب.', answerEn:'Water safety comes first: follow lifeguard or instructor directions, avoid depths beyond your ability, and never treat swimming skill as a substitute for appropriate supervision.' },
  { id:'never-swim-alone', category:'safety', keywordsAr:['لوحدي','اسبح وحدي','بدون مراقبة'], keywordsEn:['swim alone','alone','unsupervised'], answerAr:'لا يُنصح بالسباحة منفردًا في بيئة غير مراقبة، خصوصًا للمبتدئين والأطفال. وجود إشراف مناسب وخطة طوارئ جزء أساسي من السلامة.', answerEn:'Swimming alone in an unsupervised setting is not recommended, especially for beginners and children. Appropriate supervision and emergency readiness are core safety measures.' },
  { id:'pool-entry', category:'safety', keywordsAr:['انزل الميه','دخول المسبح','اقفز'], keywordsEn:['enter pool','jump in','pool entry'], answerAr:'استخدم طريقة دخول مناسبة لعمق المكان ومستواك واتبع تعليمات الموقع. القفز أو الغوص يحتاجان عمقًا ومهارة وإشرافًا مناسبين.', answerEn:'Use an entry method appropriate to the water depth and your skill, and follow venue rules. Jumping or diving requires suitable depth, skill, and supervision.' },
  { id:'pool-hygiene', category:'safety', keywordsAr:['نظافة','استحمام','كلور','هايجين'], keywordsEn:['hygiene','shower','chlorine','pool hygiene'], answerAr:'الاستحمام قبل السباحة واتباع تعليمات النظافة بالمسبح يساعدان في الحفاظ على بيئة أفضل للجميع. متطلبات الموقع المحددة تختلف من مسبح لآخر.', answerEn:'Showering before swimming and following pool hygiene rules helps maintain a better environment for everyone. Exact venue requirements vary by pool.' },
  { id:'illness', category:'safety', keywordsAr:['مريض','برد','حرارة','تعبان'], keywordsEn:['sick','ill','fever','unwell'], answerAr:'إذا كنت مريضًا أو لديك حرارة أو أعراض تؤثر على الأمان في الماء، فالأفضل تجنب التدريب حتى تكون حالتك مناسبة. للحالات الطبية المحددة استشر مختصًا.', answerEn:'If you are unwell, feverish, or have symptoms that affect water safety, it is better to avoid training until you are fit to participate. Specific medical conditions should be discussed with a clinician.' },
  { id:'injury', category:'safety', keywordsAr:['اصابة','كتف','ركبة','الم'], keywordsEn:['injury','shoulder pain','knee pain','pain'], answerAr:'الألم أو الإصابة ليست شيئًا يُفترض التدريب خلالها بلا تقييم. خفف أو أوقف النشاط المسبب للألم واطلب تقييمًا مناسبًا إذا استمر أو كان شديدًا.', answerEn:'Pain or injury should not simply be trained through without assessment. Reduce or stop the aggravating activity and seek appropriate evaluation if symptoms persist or are significant.' },
  { id:'lesson-expectations', category:'starting', keywordsAr:['الحصة بتكون ازاي','ماذا يحدث في الحصة','شكل التدريب'], keywordsEn:['what happens in a lesson','lesson structure','what to expect'], answerAr:'جلسة تعليم سباحة جيدة عادة تجمع بين مراجعة سريعة، هدف مهاري واضح، تمارين متدرجة، تطبيق عملي، ثم ملاحظات بسيطة لما يلي. تفاصيل الأكاديمية الفعلية تختلف حسب المستوى والجدول.', answerEn:'A well-structured swim lesson often combines a quick review, a clear skill goal, progressive drills, practical application, and simple next-step feedback. The academy exact format varies by level and schedule.' },
  { id:'feedback', category:'progress', keywordsAr:['ملاحظات','تصحيح','فيدباك'], keywordsEn:['feedback','correction','coach feedback'], answerAr:'الملاحظة المفيدة تكون محددة وقابلة للتنفيذ، مثل تغيير وضع الرأس أو توقيت التنفس، بدل أوامر عامة كثيرة في نفس الوقت.', answerEn:'Useful feedback is specific and actionable, such as changing head position or breathing timing, rather than giving many broad corrections at once.' },
  { id:'consistency', category:'progress', keywordsAr:['انتظام','استمرار','مواظبة'], keywordsEn:['consistency','regular','keep practicing'], answerAr:'الانتظام عادة أهم من جلسة قوية متقطعة. التكرار المنتظم لمهارة واحدة بجودة يبني التعلم العصبي والثقة بشكل أفضل.', answerEn:'Consistency usually matters more than occasional intense sessions. Repeating one skill regularly with quality supports motor learning and confidence.' },
  { id:'confidence-vs-speed', category:'progress', keywordsAr:['ثقة ولا سرعة','سرعة قبل المهارة'], keywordsEn:['confidence vs speed','speed before skill'], answerAr:'خصوصًا للمبتدئ، الثقة والتحكم والتقنية تأتي قبل السرعة. السرعة تصبح أكثر فائدة عندما يستطيع السباح الحفاظ على شكل جيد تحت الجهد.', answerEn:'Especially for beginners, confidence, control, and technique come before speed. Speed becomes more useful once the swimmer can maintain good form under effort.' },
  { id:'whatsapp-handoff-policy', category:'communication', core:true, keywordsAr:['السعر','المواعيد','العنوان','الموقع','تجربة','سيدات','المدرب'], keywordsEn:['price','schedule','address','location','trial','ladies','coach'], answerAr:'الأسعار والمواعيد والموقع الدقيق وسياسة التجربة وتوفر حصص السيدات وبيانات المدرب التفصيلية غير مؤكدة في قاعدة البيانات العامة؛ يجب تأكيدها مباشرة مع إدارة الأكاديمية عبر واتساب.', answerEn:'Pricing, schedules, exact venue, trial policy, ladies-only availability, and detailed coach credentials are not confirmed in the public data and must be confirmed directly with academy management on WhatsApp.' },
  { id:"sculling", category:"technique", keywordsAr:["سكالنج","احساس الماء","كف اليد"], keywordsEn:["sculling","feel for water","hand pressure"], answerAr:"تمارين السكالنج تساعد على الإحساس بضغط الماء وتوجيه الكف والساعد بدل الاعتماد على القوة فقط. الحركة الصغيرة الدقيقة أهم من السرعة.", answerEn:"Sculling drills can improve feel for water and awareness of pressure through the hand and forearm. Small controlled movements matter more than speed." },
  { id:"catch-phase", category:"technique", keywordsAr:["كاتش","مسكة الماء","بداية السحب"], keywordsEn:["catch","early vertical forearm","start of pull"], answerAr:"مرحلة الكاتش هي بداية تثبيت اليد والساعد على الماء قبل السحب. الهدف هو إيجاد ضغط مستقر بدل انزلاق اليد للخلف بدون فاعلية.", answerEn:"The catch is the phase where the hand and forearm establish useful pressure before the pull. The goal is stable purchase on the water rather than slipping backward." },
  { id:"freestyle-recovery", category:"technique", keywordsAr:["ريكفري","رجوع الذراع","ذراع الحرة"], keywordsEn:["freestyle recovery","arm recovery"], answerAr:"في رجوع ذراع السباحة الحرة حاول إبقاء الحركة مريحة بدون شد زائد في الكتف، مع دوران طبيعي للجذع وتجهيز دخول اليد للأمام.", answerEn:"During freestyle arm recovery, keep the movement relaxed rather than forcing the shoulder, using natural body rotation to prepare a clean hand entry." },
  { id:"hand-entry", category:"technique", keywordsAr:["دخول اليد","ايد تدخل الميه"], keywordsEn:["hand entry","entry point"], answerAr:"دخول اليد يكون عادة أمام مسار الكتف تقريبًا وبشكل هادئ، مع تجنب التقاطع الحاد نحو خط منتصف الجسم لأنه قد يربك الاتزان.", answerEn:"Hand entry is generally cleaner when it occurs roughly in front of the shoulder line, avoiding aggressive crossover toward the centerline that can disturb balance." },
  { id:"freestyle-head-position", category:"technique", keywordsAr:["وضع الراس","راسي عالية","راس الحرة"], keywordsEn:["head position","freestyle head"], answerAr:"في الحرة يفيد إبقاء الرأس هادئًا والنظر لأسفل أو قليلًا للأمام حسب الوضع، بدل رفعه باستمرار لأن ذلك قد يخفض الحوض.", answerEn:"In freestyle, a quiet head with the gaze generally down or slightly forward helps body alignment. Constantly lifting the head can encourage the hips to drop." },
  { id:"bilateral-breathing", category:"technique", keywordsAr:["تنفس على الجانبين","كل 3 حركات"], keywordsEn:["bilateral breathing","breathe both sides"], answerAr:"التنفس على الجانبين قد يساعد بعض السباحين على التوازن والوعي بالاتجاه، لكنه ليس قاعدة إلزامية. الأهم تنفس مريح لا يفسد وضع الجسم.", answerEn:"Bilateral breathing can help some swimmers with balance and orientation, but it is not mandatory. The priority is comfortable breathing that preserves body position." },
  { id:"side-balance", category:"technique", keywordsAr:["توازن على الجنب","سايد بالانس"], keywordsEn:["side balance","side position"], answerAr:"التحكم في وضع الجنب يساعد على فهم دوران الجسم والتنفس في الحرة. حاول إبقاء الجسم طويلًا والرقبة مرتاحة بدل لف الرأس وحده.", answerEn:"Side-balance work can improve understanding of body rotation and freestyle breathing. Keep the body long and the neck relaxed rather than twisting only the head." },
  { id:"body-rotation", category:"technique", keywordsAr:["دوران الجسم","روتيشن"], keywordsEn:["body rotation","rotation"], answerAr:"الدوران المتزن في الحرة والظهر يربط حركة الذراع بالجذع ويقلل الاعتماد على الكتف وحده. المبالغة في الدوران قد تسبب فقدان خط السباحة.", answerEn:"Controlled body rotation in freestyle and backstroke connects the arms with the trunk and reduces isolated shoulder effort. Excess rotation can disrupt alignment." },
  { id:"stroke-count", category:"progress", keywordsAr:["عدد الضربات","عدد الحركات"], keywordsEn:["stroke count","strokes per length"], answerAr:"عد الحركات لكل طول يمكن أن يكون مؤشرًا للكفاءة إذا قورن بنفس المسافة والسرعة والظروف. العدد الأقل ليس أفضل دائمًا لو صاحبه بطء مبالغ.", answerEn:"Stroke count per length can be an efficiency indicator when distance, speed, and conditions are comparable. Fewer strokes are not automatically better if pace collapses." },
  { id:"stroke-rate", category:"progress", keywordsAr:["معدل الحركات","كادنس","تردد الذراع"], keywordsEn:["stroke rate","cadence","tempo"], answerAr:"معدل الحركات هو سرعة تكرار دورة الذراع. زيادته مفيدة فقط عندما تظل التقنية مستقرة ولا يتحول الأداء إلى حركات قصيرة متوترة.", answerEn:"Stroke rate is how quickly the arm cycle repeats. Increasing it is useful only when technique remains stable rather than becoming short and tense." },
  { id:"pull-phase", category:"technique", keywordsAr:["السحب","مرحلة السحب"], keywordsEn:["pull phase","underwater pull"], answerAr:"السحب الفعال يحتاج مسارًا مستقرًا للساعد واليد مع جسم متزن. محاولة السحب بأقصى قوة من أول لحظة قد تضيّع الإحساس بالماء.", answerEn:"An effective underwater pull needs stable hand and forearm pressure with a balanced body. Pulling maximally from the first instant can reduce feel for the water." },
  { id:"stroke-finish", category:"technique", keywordsAr:["نهاية السحب","نهاية الحركة"], keywordsEn:["stroke finish","finish of pull"], answerAr:"نهاية حركة الذراع ينبغي أن تكون امتدادًا طبيعيًا للسحب لا دفعة عنيفة منفصلة. التركيز يكون على الاستمرارية ثم الانتقال السلس للريكفري.", answerEn:"The end of the stroke should continue the pull naturally rather than becoming a separate violent push. Aim for continuity into a relaxed recovery." },
  { id:"dolphin-kick", category:"technique", keywordsAr:["دولفين","ركلة فراشة"], keywordsEn:["dolphin kick","underwater dolphin"], answerAr:"ركلة الدولفين تبدأ كموجة مترابطة من الجذع والحوض مع ساقين متقاربتين، وليست مجرد ثني قوي للركبتين. الحجم المناسب للحركة يعتمد على السرعة والمهارة.", answerEn:"A dolphin kick is a connected wave through the trunk and hips with the legs working together, not just an aggressive knee bend. The right amplitude depends on speed and skill." },
  { id:"breaststroke-kick", category:"technique", keywordsAr:["ركلة صدر","رجلين الصدر"], keywordsEn:["breaststroke kick","frog kick"], answerAr:"ركلة الصدر تحتاج سحب الكعبين بشكل منظم ثم تدوير القدمين والدفع للخلف مع ضم الرجلين للانسياب. التوقيت مع الذراع مهم بقدر شكل الركلة.", answerEn:"Breaststroke kick uses a controlled heel recovery, outward foot position, backward press, and streamlined finish. Timing with the arms matters as much as the kick shape." },
  { id:"backstroke-kick", category:"technique", keywordsAr:["ركلة ظهر","رجلين الظهر"], keywordsEn:["backstroke kick","back kick"], answerAr:"ركلة الظهر تكون غالبًا صغيرة ومستمرة من الورك مع كاحل مرن، مع تجنب حركة ركبة كبيرة تكسر سطح الماء بلا فاعلية.", answerEn:"Backstroke kick is usually small and continuous from the hip with relaxed ankles, avoiding exaggerated knee action that breaks the surface without useful propulsion." },
  { id:"treading-water", category:"starting", keywordsAr:["دوس الميه","واقف في الميه","تريدنج"], keywordsEn:["treading water","stay upright"], answerAr:"الوقوف في الماء مهارة أمان وتحكم مهمة. يبدأ التعلم بحركات يد صغيرة ورجلين مريحة مع تنفس هادئ، ثم زيادة المدة تدريجيًا تحت إشراف مناسب.", answerEn:"Treading water is an important control and safety skill. Start with small hand movements, relaxed leg action, and calm breathing, then build duration gradually with appropriate supervision." },
  { id:"deep-water-readiness", category:"safety", keywordsAr:["مياه عميقة","عمق","ديب ووتر"], keywordsEn:["deep water","deep end"], answerAr:"الانتقال للمياه العميقة ينبغي أن يحدث فقط بعد وجود ثقة ومهارات مناسبة وقدرة على العودة للحائط أو طلب المساعدة، مع الالتزام بإشراف الموقع.", answerEn:"Moving into deep water should happen only when confidence, appropriate skills, and the ability to return to support or seek help are established, with venue supervision in place." },
  { id:"push-and-glide", category:"starting", keywordsAr:["دفع وانزلاق","ازق من الحائط"], keywordsEn:["push and glide","push off"], answerAr:"الدفع والانزلاق من الحائط يعلم خط الجسم والانسيابية. ادفع بهدوء، مد الجسم، ثم لاحظ كم تحافظ على الخط قبل بدء الحركة التالية.", answerEn:"Push-and-glide work teaches body line and streamlining. Push smoothly, extend the body, and notice how long you can hold alignment before the next movement." },
  { id:"blowing-bubbles", category:"starting", keywordsAr:["فقاقيع","اطلع الهوا في الميه"], keywordsEn:["blow bubbles","exhale underwater"], answerAr:"إخراج فقاعات داخل الماء تمرين بسيط لتعلم الزفير بدل حبس النفس. يمكن البدء بالوجه قريبًا من السطح ثم التدرج حسب الراحة.", answerEn:"Blowing bubbles is a simple way to learn underwater exhalation instead of breath-holding. Begin close to the surface and progress only as comfort improves." },
  { id:"submersion-comfort", category:"starting", keywordsAr:["ادخل وشي","اغطس راسي","تحت الميه"], keywordsEn:["put face in water","submerge","underwater comfort"], answerAr:"الراحة في إدخال الوجه للماء تتطور بالتدرج: لمس الماء، فقاعات، إدخال الوجه لثوانٍ قصيرة، ثم زيادة الوقت بدون إجبار.", answerEn:"Comfort with putting the face in water develops gradually: touch the water, blow bubbles, submerge briefly, then increase duration without forcing the process." },
  { id:"wall-support", category:"safety", keywordsAr:["امسك الحائط","جنب الحائط"], keywordsEn:["hold the wall","wall support"], answerAr:"الحائط نقطة أمان مهمة للمبتدئ. تعلم الوصول له والإمساك به والدوران والوقوف قبل الابتعاد لمسافات أكبر.", answerEn:"The pool wall is an important safety reference for beginners. Learn to reach it, hold it, turn, and regain footing before moving farther away." },
  { id:"kickboard-basics", category:"starting", keywordsAr:["لوح","كيك بورد"], keywordsEn:["kickboard","kick board"], answerAr:"اللوح يمكن أن يعزل تمرين الرجلين، لكنه قد يغيّر وضع الجسم إذا تم رفع الرأس بقوة. استخدمه كأداة تدريب وليس كبديل عن وضع السباحة الطبيعي.", answerEn:"A kickboard can isolate leg work, but it can alter body position if the head is held too high. Use it as a training tool rather than a substitute for natural swimming posture." },
  { id:"first-25m", category:"progress", keywordsAr:["اول 25 متر","25 متر","اول طول"], keywordsEn:["first 25","first length","25 meters"], answerAr:"الهدف من أول مسافة كاملة ليس السرعة؛ الأفضل المحافظة على تنفس هادئ وشكل مقبول حتى النهاية. يمكن تقسيم المسافة أولًا ثم جمعها تدريجيًا.", answerEn:"The goal of a first full length is not speed. Aim to preserve calm breathing and reasonable form to the end, building from shorter sections if needed." },
  { id:"underwater-orientation", category:"safety", keywordsAr:["اتجاهي تحت الميه","مش عارف فين"], keywordsEn:["underwater orientation","where am i underwater"], answerAr:"القدرة على معرفة مكان السطح والحائط بعد غمر قصير مهارة تحكم مهمة. تدرب في بيئة مراقبة وقريبة من نقطة دعم حتى تصبح الحركة مألوفة.", answerEn:"Knowing where the surface and wall are after brief submersion is an important control skill. Practice in a supervised setting close to support until orientation feels familiar." },
  { id:"drill-purpose", category:"progress", keywordsAr:["دريل","تمرين مهاري","تمارين تكنيك"], keywordsEn:["drill","skill drill","technique drill"], answerAr:"التمرين المهاري يكون مفيدًا عندما يخدم نقطة واضحة مثل التوازن أو الكاتش أو التنفس. تنفيذ الدريل بدون ربطه بالسباحة الكاملة قد يقلل فائدته.", answerEn:"A drill is most useful when it targets a clear point such as balance, catch, or breathing. Doing drills without transferring the skill back into full swimming can limit their value." },
  { id:"drill-to-swim-transfer", category:"progress", keywordsAr:["انقل الدريل للسباحة","تطبيق الدريل"], keywordsEn:["transfer drill to swim","drill transfer"], answerAr:"بعد الدريل جرب مسافة قصيرة سباحة كاملة مع التركيز على نفس الإحساس. هذا يساعد على تحويل المهارة من تمرين معزول إلى أداء فعلي.", answerEn:"After a drill, swim a short full-stroke segment while focusing on the same sensation. This helps transfer the isolated skill into real swimming." },
  { id:"pacing-basics", category:"progress", keywordsAr:["تقسيم السرعة","بايس","سرعة ثابتة"], keywordsEn:["pacing","pace","even pace"], answerAr:"تقسيم الجهد يعني البدء بسرعة يمكن الحفاظ عليها ثم تعديلها تدريجيًا. الانطلاق بأقصى سرعة غالبًا يؤدي لانهيار التقنية مبكرًا.", answerEn:"Pacing means starting at an effort you can sustain and adjusting deliberately. Going all-out immediately often causes technique to break down early." },
  { id:"interval-training", category:"fitness", keywordsAr:["انترفالات","فترات","مجموعات"], keywordsEn:["intervals","interval training","sets"], answerAr:"تدريب الفترات يقسم العمل إلى مسافات أو أزمنة مع راحة محددة. الهدف قد يكون التقنية أو التحمل أو السرعة، لذلك شكل المجموعة يتغير حسب الهدف.", answerEn:"Interval training divides work into repeat distances or times with defined rest. The set design changes depending on whether the goal is technique, endurance, or speed." },
  { id:"rest-intervals", category:"fitness", keywordsAr:["راحة بين الجولات","وقت الراحة"], keywordsEn:["rest interval","rest between reps"], answerAr:"الراحة بين التكرارات جزء من تصميم التمرين. راحة أطول تسمح بجودة وسرعة أعلى، وراحة أقصر ترفع تحدي الاستمرارية والتحمل.", answerEn:"Rest between repeats is part of the workout design. Longer rest supports higher quality and speed, while shorter rest increases the continuity and endurance challenge." },
  { id:"skill-tracking", category:"progress", keywordsAr:["اسجل تقدمي","متابعة التقدم","قياس"], keywordsEn:["track progress","measure progress","training log"], answerAr:"تسجيل هدف بسيط لكل حصة مثل عدد أطوال بجودة جيدة أو استقرار التنفس يجعل التقدم أوضح من الاعتماد على الإحساس العام فقط.", answerEn:"Tracking one simple target per session, such as quality lengths or stable breathing, can make progress clearer than relying only on general impressions." },
  { id:"video-feedback", category:"progress", keywordsAr:["فيديو","تصوير السباحة","تحليل فيديو"], keywordsEn:["video feedback","film my swimming","video analysis"], answerAr:"الفيديو قد يكشف فروقًا بين الإحساس والحركة الفعلية، خصوصًا في وضع الرأس والدخول والدوران. استخدامه يكون أفضل مع هدف واحد واضح في كل مراجعة.", answerEn:"Video can reveal differences between what a swimmer feels and what is actually happening, especially in head position, entry, and rotation. Review one clear target at a time." },
  { id:"fatigue-technique", category:"progress", keywordsAr:["التكنيك بيبوظ مع التعب","اتعب"], keywordsEn:["technique breaks when tired","fatigue form"], answerAr:"عندما تبدأ التقنية في الانهيار مع التعب، من الأفضل تقليل السرعة أو أخذ راحة قصيرة بدل تثبيت حركة سيئة بتكرار كثير.", answerEn:"When technique starts to break down under fatigue, reducing speed or taking a short rest is often better than reinforcing poor movement through more repetitions." },
  { id:"weekly-consistency", category:"progress", keywordsAr:["انتظام اسبوعي","كل اسبوع"], keywordsEn:["weekly consistency","regular weekly practice"], answerAr:"الانتظام الأسبوعي يبني الاعتياد والمهارة بشكل أفضل من فترات نشاط قوية يتبعها انقطاع طويل. عدد الجلسات الفعلي يعتمد على ظروف الشخص والبرنامج.", answerEn:"Weekly consistency builds familiarity and skill better than bursts of hard training followed by long gaps. The actual number of sessions depends on the person and program." },
  { id:"return-after-break", category:"progress", keywordsAr:["راجعت بعد توقف","بعد انقطاع","وقفت فترة"], keywordsEn:["return after break","back after time off"], answerAr:"بعد انقطاع ابدأ بحجم وشدة أقل من آخر مستوى تتذكره، وركز على الإحساس بالماء والتنفس قبل استعادة المسافات أو السرعات السابقة.", answerEn:"After a break, restart below your remembered peak volume and intensity. Rebuild feel for water and breathing before chasing previous distance or speed." },
  { id:"competition-readiness", category:"progress", keywordsAr:["بطولة","منافسة","سباق"], keywordsEn:["competition","race readiness","swim meet"], answerAr:"الاستعداد للسباق يحتاج تقنية مستقرة، معرفة بالقواعد، قدرة على تنفيذ البداية والدورانات المناسبة، وخطة جهد. المشاركة الفعلية تعتمد على برنامج الأكاديمية والمتطلبات المنظمة.", answerEn:"Race readiness involves stable technique, rule awareness, suitable starts and turns, and a pacing plan. Actual competition participation depends on the academy program and event requirements." },
  { id:"personal-best", category:"progress", keywordsAr:["رقم شخصي","احسن زمن","بي بي"], keywordsEn:["personal best","best time","pb"], answerAr:"الزمن الشخصي مفيد كمؤشر لكنه ليس القياس الوحيد. تحسن التقنية والاتساق وعدد الحركات قد يسبق تحسن الزمن ثم ينعكس عليه لاحقًا.", answerEn:"A personal best is useful but not the only progress marker. Improvements in technique, consistency, and stroke efficiency may come before a faster time." },
  { id:"child-lesson-readiness", category:"parents", keywordsAr:["طفلي جاهز للحصة","جاهزية الطفل"], keywordsEn:["child ready for lessons","lesson readiness"], answerAr:"جاهزية الطفل لا تعتمد على العمر فقط؛ الانتباه للتعليمات والقدرة على الابتعاد القصير عن ولي الأمر والراحة مع الماء كلها مؤشرات مهمة.", answerEn:"A child's readiness for lessons is not only about age. Following simple instructions, tolerating brief separation, and basic comfort around water are useful indicators." },
  { id:"praise-process", category:"parents", keywordsAr:["اشجع طفلي","مدح الطفل"], keywordsEn:["praise child","encourage child"], answerAr:"مدح المجهود والشجاعة والمحاولة أفضل عادة من التركيز على الفوز أو المقارنة. هذا يساعد الطفل يربط التعلم بالتقدم لا بالخوف من الخطأ.", answerEn:"Praising effort, courage, and trying is usually more useful than focusing on winning or comparison. It helps children connect learning with progress rather than fear of mistakes." },
  { id:"parent-observation", category:"parents", keywordsAr:["اتفرج على الحصة","ولي الامر يشاهد"], keywordsEn:["watch lesson","parent observe lesson"], answerAr:"بعض الأطفال يركزون أفضل مع وجود ولي الأمر وبعضهم يتشتت. سياسة المشاهدة الفعلية تختلف حسب الموقع والمدرب وتحتاج تأكيد الإدارة.", answerEn:"Some children focus better with a parent nearby while others become distracted. The actual observation policy depends on the venue and coach and needs management confirmation." },
  { id:"avoid-comparison", category:"parents", keywordsAr:["اقارن ابني","مقارنة الاطفال"], keywordsEn:["compare children","compare my child"], answerAr:"مقارنة طفل بطفل آخر قد تخلق ضغطًا غير مفيد لأن سرعة التعلم تختلف. الأفضل مقارنة الطفل بنفسه: راحته، استقلاله، وتقنيته عبر الوقت.", answerEn:"Comparing one child with another can create unnecessary pressure because learning rates differ. Compare the child with their own previous confidence, independence, and technique instead." },
  { id:"separation-anxiety", category:"parents", keywordsAr:["يبكي في الحصة","مش عايز يبعد عني"], keywordsEn:["separation anxiety","cries in lesson"], answerAr:"لو الطفل متوتر من الانفصال، التدرج والروتين الثابت يساعدان أكثر من الضغط. نجاح قصير وهادئ أفضل من إجباره على حصة كاملة وهو منهار.", answerEn:"If a child struggles with separation, gradual exposure and a predictable routine are often more helpful than pressure. A short calm success can be better than forcing a full distressed session." },
  { id:"child-goggles", category:"parents", keywordsAr:["نظارة للطفل","جوجلز اطفال"], keywordsEn:["kids goggles","child goggles"], answerAr:"اختيار نظارة الطفل يعتمد على الراحة والإغلاق الجيد بدون ضغط قوي. جرّب المقاس على الوجه بدل الاعتماد على العمر المكتوب فقط.", answerEn:"Children's goggles should fit comfortably and seal without excessive pressure. Testing fit on the face is more useful than relying only on the age label." },
  { id:"adult-returning-swimmer", category:"adults", keywordsAr:["كنت بعرف ونسيت","راجع للسباحة"], keywordsEn:["returning swimmer","used to swim"], answerAr:"لو كنت تعرف السباحة ثم توقفت، ابدأ باستعادة التنفس والإحساس بالماء والتكنيك قبل رفع المسافة أو السرعة. الجسم قد يتذكر الحركة لكن التحمل يحتاج وقتًا.", answerEn:"If you used to swim and are returning, rebuild breathing, feel for water, and technique before increasing distance or speed. Movement memory may return before endurance does." },
  { id:"adult-past-bad-experience", category:"adults", keywordsAr:["تجربة سيئة","غرقت قبل كده","حادث ماء"], keywordsEn:["bad water experience","previous scare","near drowning fear"], answerAr:"بعد تجربة ماء مخيفة، التدرج والبيئة المراقبة مهمان. ابدأ بمهام قصيرة تشعرك بالتحكم ولا تتجاوز مستوى الراحة فجأة.", answerEn:"After a frightening water experience, gradual exposure in a supervised environment matters. Start with short tasks that restore control rather than suddenly pushing beyond comfort." },
  { id:"adult-mobility", category:"adults", keywordsAr:["مرونة","تيبس","حركة الكتف"], keywordsEn:["mobility","stiff","shoulder mobility"], answerAr:"مدى الحركة يؤثر على راحة السباحة لكنه ليس لازمًا يكون مثاليًا من البداية. التقنية يمكن تعديلها حسب قدرة الشخص مع تحسين الحركة تدريجيًا.", answerEn:"Mobility affects swimming comfort, but it does not need to be perfect at the start. Technique can be adapted to current ability while mobility improves gradually." },
  { id:"adult-stamina-build", category:"adults", keywordsAr:["نفس قصير","بتعب بسرعة كبير"], keywordsEn:["adult stamina","out of breath quickly"], answerAr:"للكبار الذين يتعبون بسرعة، تقسيم المسافة لمقاطع قصيرة مع راحة كافية يساعد على الحفاظ على التقنية وبناء التحمل تدريجيًا.", answerEn:"For adults who tire quickly, breaking distance into shorter repeats with enough rest helps preserve technique while endurance builds gradually." },
  { id:"beginner-embarrassment", category:"adults", keywordsAr:["مكسوف اتعلم","احراج مبتدئ"], keywordsEn:["embarrassed beginner","too embarrassed"], answerAr:"البدء كمبتدئ في سن كبير أمر طبيعي، ومقارنة نفسك بسباح متقدم لا تساعد. ركز على مهارة واحدة في كل مرة وعلى تقدمك الشخصي.", answerEn:"Starting as an adult beginner is normal, and comparing yourself with advanced swimmers is rarely useful. Focus on one skill at a time and your own progress." },
  { id:"individual-learning-pace", category:"progress", keywordsAr:["بتعلم ببطء","سرعة التعلم"], keywordsEn:["learning pace","slow learner"], answerAr:"سرعة تعلم السباحة تختلف حسب الخبرة السابقة والثقة والتكرار والحركة الجسدية. البطء في مرحلة لا يعني عدم القدرة على الوصول لمستوى جيد.", answerEn:"Swimming learning speed varies with prior experience, confidence, repetition, and movement ability. Slow progress in one phase does not mean you cannot reach a strong level." },
  { id:"sun-protection", category:"preparation", keywordsAr:["شمس","واقي شمس","مسبح خارجي"], keywordsEn:["sun protection","sunscreen","outdoor pool"], answerAr:"في المسبح الخارجي يفيد استخدام وسائل حماية مناسبة من الشمس والالتزام بتعليمات المنتج، مع إعادة التطبيق عند الحاجة حسب التعليمات.", answerEn:"For outdoor swimming, appropriate sun protection is useful. Follow the product instructions and reapply when needed according to the label." },
  { id:"pool-deck-footwear", category:"safety", keywordsAr:["شبشب","ارض المسبح","تزحلق"], keywordsEn:["pool deck shoes","slippery deck","flip flops"], answerAr:"أرضية المسبح قد تكون زلقة، لذلك امشِ بهدوء واستخدم حذاء مناسب للمناطق المبللة إذا سمحت سياسة الموقع.", answerEn:"Pool decks can be slippery, so walk carefully and use suitable footwear for wet areas when venue rules allow it." },
  { id:"jewelry-before-swim", category:"preparation", keywordsAr:["مجوهرات","ساعة","خاتم"], keywordsEn:["jewelry","watch","ring"], answerAr:"من العملي إزالة الأشياء التي قد تضيع أو تعيق الحركة قبل السباحة، مثل بعض الحلي أو الإكسسوارات، حسب سياسة المسبح.", answerEn:"It is practical to remove items that could be lost or interfere with movement before swimming, such as some jewelry or accessories, subject to venue policy." },
  { id:"contact-lenses", category:"preparation", keywordsAr:["عدسات","عدسات لاصقة"], keywordsEn:["contact lenses","contacts in pool"], answerAr:"استخدام العدسات اللاصقة في الماء له اعتبارات صحية تختلف حسب نوع العدسة والبيئة. الأفضل اتباع إرشادات مختص العيون وتعليمات العدسات.", answerEn:"Contact lenses in water have health considerations that vary by lens type and environment. Follow eye-care professional guidance and the lens instructions." },
  { id:"ear-comfort", category:"preparation", keywordsAr:["ودني","اذني","مياه في الاذن"], keywordsEn:["ear water","ear comfort","ear plugs"], answerAr:"إذا كانت المياه في الأذن تسبب لك مشكلة متكررة، استخدم وسائل مناسبة فقط إذا كانت ملائمة لك وتابع أي ألم أو أعراض مستمرة مع مختص.", answerEn:"If water in the ears is a recurring problem, use suitable solutions only when appropriate for you, and seek professional advice for persistent pain or symptoms." },
  { id:"post-swim-rinse", category:"preparation", keywordsAr:["بعد السباحة","استحمام بعد","اشطف"], keywordsEn:["after swimming","rinse after pool","shower after"], answerAr:"الاستحمام وشطف الجلد والشعر بعد السباحة قد يكون مريحًا ويساعد على إزالة بقايا ماء المسبح، ثم تجفيف الجسم وتغيير الملابس المبللة.", answerEn:"Rinsing skin and hair after swimming can be comfortable and helps remove pool-water residue, followed by drying off and changing out of wet clothing." },
  { id:"pre-swim-snack", category:"preparation", keywordsAr:["اكل قبل السباحة","سناك"], keywordsEn:["eat before swimming","pre swim snack"], answerAr:"قبل التدريب يفضل كثير من الناس وجبة أو سناك خفيف يناسبهم بدل طعام ثقيل قريب جدًا من الجلسة. الاحتياجات تختلف من شخص لآخر.", answerEn:"Many people prefer a light meal or snack that sits comfortably before training rather than a heavy meal immediately beforehand. Individual needs vary." },
  { id:"locker-prep", category:"preparation", keywordsAr:["لوكر","خزانة","اغراضي"], keywordsEn:["locker","belongings","storage"], answerAr:"جهّز طريقة آمنة لحفظ الهاتف والمفاتيح والأشياء الثمينة حسب إمكانات الموقع. لا تفترض وجود خزانة أو قفل إلا بعد تأكيد المكان.", answerEn:"Plan a safe way to store your phone, keys, and valuables according to the venue facilities. Do not assume lockers or locks are available without confirmation." },
  { id:"extra-towel", category:"preparation", keywordsAr:["منشفة","فوطة"], keywordsEn:["towel","extra towel"], answerAr:"منشفة مناسبة وملابس جافة بعد الحصة تجعل الانتقال بعد السباحة أريح، خصوصًا للأطفال أو في الأجواء الباردة.", answerEn:"A suitable towel and dry clothes make the transition after swimming more comfortable, especially for children or in cooler conditions." },
  { id:"lane-etiquette", category:"safety", keywordsAr:["مسار السباحة","لين","زحمة المسار"], keywordsEn:["lane etiquette","lap lane","circle swim"], answerAr:"في المسارات المشتركة اتبع اتجاه السباحة وتعليمات الموقع، واترك مسافة مناسبة وتجنب التوقف في منتصف المسار.", answerEn:"In shared lanes, follow the venue direction, leave appropriate space, and avoid stopping in the middle of the lane." },
  { id:"cramp-response", category:"safety", keywordsAr:["شد عضلي","كرامب","تقلص"], keywordsEn:["cramp","muscle cramp"], answerAr:"لو حدث شد عضلي في الماء، توقف عن الجهد واطلب الدعم أو اتجه لنقطة أمان بدل محاولة الاستمرار بالقوة. الأعراض الشديدة أو المتكررة تحتاج تقييمًا مناسبًا.", answerEn:"If a muscle cramp occurs in the water, stop hard effort and move toward support or ask for help rather than forcing through it. Severe or recurring symptoms deserve appropriate evaluation." },
  { id:"breath-hold-safety", category:"safety", keywordsAr:["حبس النفس","تحت الماء وقت طويل","هايبرفنتليشن"], keywordsEn:["breath hold","underwater breath holding","hyperventilation"], answerAr:"تمارين حبس النفس الطويل تحت الماء قد تكون خطرة، خصوصًا مع فرط التنفس قبلها. لا تُمارس تحديات حبس النفس منفردًا أو بدون إشراف متخصص مناسب.", answerEn:"Long underwater breath-hold challenges can be dangerous, especially after hyperventilation. Do not practice breath-hold challenges alone or without appropriate specialist supervision." },
  { id:"aerobic-base", category:"fitness", keywordsAr:["ايروبيك","قاعدة هوائية","تحمل اساسي"], keywordsEn:["aerobic base","easy endurance"], answerAr:"القاعدة الهوائية تُبنى غالبًا بجهد يمكن الحفاظ عليه مع تقنية مستقرة وتنفس منظم. الهدف ليس السباحة البطيئة فقط بل تكرار جودة الحركة لفترة أطول.", answerEn:"An aerobic base is often built at an effort that can be sustained with stable technique and controlled breathing. The goal is not merely slow swimming but repeating quality movement for longer." },
  { id:"sprint-quality", category:"fitness", keywordsAr:["سبرنت","سرعات قصيرة","اقصى سرعة"], keywordsEn:["sprint","short speed","max speed"], answerAr:"السرعات القصيرة تكون أكثر فائدة عندما تبدأ من وضع جيد وتكنيك ثابت. لو فقدت شكل الحركة تمامًا، أوقف التكرار أو زد الراحة.", answerEn:"Short sprints are more useful when they begin from good alignment and stable technique. If movement quality falls apart, stop the repeat or increase recovery." },
  { id:"recovery-swim", category:"fitness", keywordsAr:["سباحة استشفاء","ريكفري سباحة"], keywordsEn:["recovery swim","easy swim"], answerAr:"السباحة السهلة بعد مجهود قوي قد تساعد على تهدئة الإيقاع والحفاظ على الحركة بدون إضافة ضغط كبير. الشدة ينبغي أن تكون مريحة فعلًا.", answerEn:"Easy swimming after harder work can help settle the rhythm and maintain movement without adding much stress. The intensity should genuinely feel easy." },
  { id:"dryland-basics", category:"fitness", keywordsAr:["تمارين خارج الماء","دراي لاند"], keywordsEn:["dryland","land training"], answerAr:"التمارين خارج الماء يمكن أن تدعم القوة والثبات والحركة، لكنها لا تعوض وقت تعلم المهارة داخل الماء. اختر تمارين مناسبة لمستواك وحالتك.", answerEn:"Dryland training can support strength, stability, and movement, but it does not replace skill practice in the water. Choose exercises appropriate to your level and condition." },
  { id:"shoulder-mobility-general", category:"fitness", keywordsAr:["كتف السباح","مرونة الكتف"], keywordsEn:["swimmer shoulder mobility","shoulder mobility"], answerAr:"حركة الكتف الجيدة تساعد على راحة السباحة، لكن لا تدفع المفصل إلى مدى مؤلم. ألم الكتف المستمر يحتاج تقييمًا متخصصًا بدل الاستمرار عليه.", answerEn:"Useful shoulder mobility can make swimming more comfortable, but do not force painful ranges. Persistent shoulder pain should be professionally assessed rather than trained through." },
  { id:"core-control", category:"fitness", keywordsAr:["كور","عضلات البطن","ثبات الجذع"], keywordsEn:["core","trunk control","body stability"], answerAr:"ثبات الجذع يساعد على نقل القوة والحفاظ على خط الجسم بدل تمايله. الهدف ليس شد البطن بأقصى قوة بل تحكم مستمر ومريح.", answerEn:"Trunk control helps transfer force and maintain body alignment rather than excessive side-to-side movement. The goal is steady control, not maximal bracing." },
  { id:"kick-set-purpose", category:"fitness", keywordsAr:["مجموعة رجلين","كيك ست"], keywordsEn:["kick set","kick training"], answerAr:"مجموعات الرجلين قد تستهدف التحمل أو التقنية أو السرعة حسب تصميمها. حافظ على وضع جسم جيد بدل تحويل التمرين إلى مجرد ركلات كثيرة.", answerEn:"Kick sets can target endurance, technique, or speed depending on design. Preserve body position rather than turning the set into high-volume kicking without control." },
  { id:"pull-buoy-use", category:"fitness", keywordsAr:["بول بوي","سحب فقط"], keywordsEn:["pull buoy","pull set"], answerAr:"البول بوي يرفع الرجلين ويسمح بالتركيز على الذراعين ووضع الجذع، لكنه يغيّر توازن الجسم الطبيعي، لذلك يُستخدم كأداة محددة لا طوال الوقت.", answerEn:"A pull buoy supports the legs and lets you focus on the arms and trunk position, but it changes natural balance, so it is best used as a specific tool rather than constantly." },
  { id:"fins-use", category:"fitness", keywordsAr:["زعانف","فينز"], keywordsEn:["fins","swim fins"], answerAr:"الزعانف يمكن أن تساعد على الإيقاع ووضع الجسم والإحساس بالسرعة، لكن المقاس المناسب والجرعة المعقولة مهمان لتجنب إجهاد غير ضروري.", answerEn:"Fins can help rhythm, body position, and speed awareness, but proper fit and sensible volume matter to avoid unnecessary strain." },
  { id:"paddles-use", category:"fitness", keywordsAr:["بادلز","مجاديف اليد"], keywordsEn:["paddles","hand paddles"], answerAr:"مجاديف اليد تزيد الإحساس بالماء والحمل على الذراع، لذلك ليست أداة للمبتدئ لمجرد زيادة القوة. الحجم الكبير أو الاستخدام المفرط قد يزيد حمل الكتف.", answerEn:"Hand paddles increase water pressure and upper-body load, so they are not simply a beginner strength tool. Oversized paddles or excessive use can increase shoulder stress." },
  { id:"coach-goal-conversation", category:"communication", keywordsAr:["اقول للمدرب هدفي","اكلم المدرب"], keywordsEn:["tell coach my goal","talk to coach"], answerAr:"عند التواصل مع المدرب اشرح هدفك الحالي وخبرتك وما الذي يسبب لك صعوبة. معلومات محددة مثل الخوف من الماء أو مشكلة التنفس تساعد على اختيار بداية أنسب.", answerEn:"When speaking with a coach, share your current goal, experience, and what feels difficult. Specific details such as water fear or breathing difficulty help identify a better starting point." },
  { id:"booking-info-to-share", category:"communication", keywordsAr:["ايه البيانات للحجز","معلومات الحجز"], keywordsEn:["booking information","what details to send"], answerAr:"عند التواصل للحجز من المفيد ذكر الاسم، العمر التقريبي للمتدرب، المستوى الحالي، الهدف، والوقت المفضل. السعر والموقع والموعد النهائي تؤكدهم الإدارة مباشرة.", answerEn:"When asking to book, it helps to share the swimmer name, approximate age, current level, goal, and preferred time. Management should confirm final pricing, venue, and schedule directly." },
];

function normalize(input: string): string {
  return input.toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F]/g, '').replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim();
}

export interface KnowledgeMatch {
  readonly article: KnowledgeArticle;
  readonly score: number;
}

export function searchAcademyKnowledge(query: string, locale: 'ar' | 'en', limit = 6): readonly KnowledgeMatch[] {
  const normalized = normalize(query);
  if (!normalized) {
    return ACADEMY_KNOWLEDGE.filter((article) => article.core).slice(0, limit).map((article) => ({ article, score: 1 }));
  }
  const tokens = new Set(normalized.split(' ').filter((token) => token.length > 1));
  const ranked = ACADEMY_KNOWLEDGE.map((article) => {
    const keywords = [...article.keywordsAr, ...article.keywordsEn].map(normalize);
    let score = article.core ? 0.15 : 0;
    for (const keyword of keywords) {
      if (!keyword) continue;
      if (normalized.includes(keyword)) score += keyword.includes(' ') ? 4 : 3;
      for (const token of keyword.split(' ')) if (tokens.has(token) && token.length > 2) score += 0.5;
    }
    return { article, score };
  }).filter((match) => match.score > 0.15).sort((a, b) => b.score - a.score || a.article.id.localeCompare(b.article.id));
  return ranked.slice(0, limit);
}

export function knowledgeText(article: KnowledgeArticle, locale: 'ar' | 'en'): string {
  return locale === 'ar' ? article.answerAr : article.answerEn;
}

export function bestKnowledgeAnswer(query: string, locale: 'ar' | 'en'): string | null {
  const [best] = searchAcademyKnowledge(query, locale, 1);
  return best && best.score >= 1 ? knowledgeText(best.article, locale) : null;
}

export function knowledgeContext(query: string, locale: 'ar' | 'en', limit = 7): string {
  return searchAcademyKnowledge(query, locale, limit).map(({ article }) => `- [${article.category}/${article.id}] ${knowledgeText(article, locale)}`).join('\n');
}

export const KNOWLEDGE_ARTICLE_COUNT = ACADEMY_KNOWLEDGE.length;
