export type KnowledgeCategory = 'academy' | 'starting' | 'technique' | 'progress' | 'safety' | 'parents' | 'adults' | 'preparation' | 'fitness' | 'communication';

export interface KnowledgeArticle {
  readonly id: string;
  readonly category: KnowledgeCategory;
  readonly keywordsAr: readonly string[];
  readonly keywordsEn: readonly string[];
  readonly answerAr: string;
  readonly answerEn: string;
  readonly core?: boolean;
}

export const ACADEMY_KNOWLEDGE: readonly KnowledgeArticle[] = [
  { id:'academy-overview', category:'academy', core:true, keywordsAr:['الاكاديمية','سويم فيت','swim fit','من انتم'], keywordsEn:['academy','swim fit','who are you','about'], answerAr:'سويم فيت أكاديمي تقدم تعليم سباحة لجميع المستويات في أبوظبي، مع تجربة رقمية ثنائية اللغة بالعربية والإنجليزية.', answerEn:'Swim Fit Academy provides swimming instruction for all levels in Abu Dhabi, with a bilingual Arabic and English digital experience.' },
  { id:'academy-levels', category:'academy', core:true, keywordsAr:['المستويات','كل المستويات','مبتدئ','متقدم'], keywordsEn:['levels','all levels','beginner','advanced'], answerAr:'المعلومة المؤكدة حاليًا أن الأكاديمية تخدم جميع المستويات. تحديد المستوى المناسب يبدأ بفهم خبرتك الحالية وهدفك في الماء.', answerEn:'The confirmed academy scope is all levels. The right starting point depends on your current water experience and your goal.' },
  { id:'academy-language', category:'academy', core:true, keywordsAr:['عربي','انجليزي','اللغة','لغة'], keywordsEn:['arabic','english','language','bilingual'], answerAr:'الموقع والمساعد يدعمان العربية والإنجليزية، ويمكنك الاستمرار باللغة التي تفضلها.', answerEn:'The website and assistant support Arabic and English, so you can continue in whichever language you prefer.' },
  { id:'academy-phone', category:'communication', core:true, keywordsAr:['رقم','هاتف','اتصال','تليفون'], keywordsEn:['phone','number','call','telephone'], answerAr:'رقم التواصل المؤكد هو 056 969 8628، وبالصيغة الدولية +971 56 969 8628.', answerEn:'The confirmed contact number is 056 969 8628, or +971 56 969 8628 internationally.' },
  { id:'academy-whatsapp', category:'communication', core:true, keywordsAr:['واتساب','واتس','راسل','تواصل'], keywordsEn:['whatsapp','message','text','contact'], answerAr:'يمكنك التواصل مباشرة عبر واتساب على الرقم +971 56 969 8628. التفاصيل المتغيرة مثل الأسعار والمواعيد والموقع الدقيق تحتاج تأكيد الإدارة.', answerEn:'You can contact the academy directly on WhatsApp at +971 56 969 8628. Variable details such as pricing, schedules, and exact venue need management confirmation.' },
  { id:'academy-facebook', category:'communication', keywordsAr:['فيسبوك','فيس بوك','صفحة'], keywordsEn:['facebook','social page'], answerAr:'يوجد رابط فيسبوك مدعوم ضمن بيانات الأكاديمية العامة. أي حساب اجتماعي آخر لا يُعرض كرسمي إلا بعد التحقق.', answerEn:'A supported Facebook page is part of the academy public data. Other social accounts are not presented as official until verified.' },
  { id:'first-time-swimmer', category:'starting', core:true, keywordsAr:['اول مرة','من الصفر','لا اعرف السباحة','مش بعرف اسبح'], keywordsEn:['first time','from scratch','never swam','cannot swim'], answerAr:'لو دي أول مرة، البداية الطبيعية تكون بالراحة في الماء، التحكم في التنفس، الطفو، وضع الجسم، ثم الحركة الأساسية. التقدم يكون خطوة بخطوة وليس بالقفز لمهارات صعبة.', answerEn:'For a first-time swimmer, a sensible path is water comfort, breathing control, floating, body position, then basic movement. Progress should be step by step rather than jumping into advanced skills.' },
  { id:'water-confidence', category:'starting', keywordsAr:['خوف','خايف','ثقة','توتر','رهبة الماء'], keywordsEn:['fear','afraid','confidence','nervous','water anxiety'], answerAr:'الخوف من الماء شائع، والأفضل التعامل معه تدريجيًا: دخول آمن، تنفس هادئ، تمارين قصيرة للوجه والطفو، ثم زيادة التحدي عند الشعور بالراحة.', answerEn:'Fear of water is common. A gradual approach works best: safe entry, calm breathing, short face-in-water and floating drills, then increasing difficulty only when comfortable.' },
  { id:'breathing-basics', category:'technique', keywordsAr:['تنفس','النفس','اخد نفس','زفير'], keywordsEn:['breathing','breath','exhale','inhale'], answerAr:'أساس التنفس في السباحة هو إخراج الهواء بهدوء داخل الماء وأخذ الشهيق بسرعة عند توفر الوضع المناسب، بدل حبس النفس لفترة طويلة.', answerEn:'A core swimming breathing habit is to exhale steadily in the water and take a quick inhale when the body position allows it, rather than holding your breath for too long.' },
  { id:'floating-basics', category:'starting', keywordsAr:['طفو','اعوم','افرد جسمي'], keywordsEn:['float','floating','stay up'], answerAr:'الطفو يعتمد على الاسترخاء ووضع الجسم والتنفس أكثر من القوة. شد الجسم أو رفع الرأس بقوة غالبًا يجعل الرجلين تهبطان.', answerEn:'Floating depends more on relaxation, body position, and breathing than strength. Tensing up or lifting the head aggressively often makes the legs sink.' },
  { id:'streamline', category:'technique', keywordsAr:['انسيابية','ستريم لاين','مقاومة الماء'], keywordsEn:['streamline','drag','water resistance'], answerAr:'الوضع الانسيابي يقلل مقاومة الماء: جسم ممتد، رأس بين الذراعين، وخط جسم طويل قدر الإمكان بعد الدفع.', answerEn:'A streamlined body reduces drag: long body line, head between the arms, and a compact shape after pushing off.' },
  { id:'freestyle', category:'technique', keywordsAr:['حرة','فري ستايل','كراول'], keywordsEn:['freestyle','front crawl','crawl'], answerAr:'في السباحة الحرة ركّز على وضع جسم مستقر، دوران بسيط للجذع، دخول يد نظيف، سحب فعال، وتنفس منتظم بدون رفع الرأس للأعلى.', answerEn:'For freestyle, focus on stable body position, controlled body rotation, clean hand entry, effective pull, and rhythmic breathing without lifting the head upward.' },
  { id:'backstroke', category:'technique', keywordsAr:['ظهر','باك ستروك'], keywordsEn:['backstroke','back stroke'], answerAr:'سباحة الظهر تحتاج وضع حوض مرتفع نسبيًا، رأس ثابت، ركلة مستمرة خفيفة، وتدوير متوازن للكتفين أثناء حركة الذراعين.', answerEn:'Backstroke benefits from a relatively high hip position, quiet head, light continuous kick, and balanced shoulder rotation through the arm cycle.' },
  { id:'breaststroke', category:'technique', keywordsAr:['صدر','براست ستروك'], keywordsEn:['breaststroke','breast stroke'], answerAr:'في سباحة الصدر التوقيت مهم: سحب، تنفس، ركلة، ثم انسياب. الاستعجال بين المراحل يقلل الكفاءة.', answerEn:'Breaststroke is highly timing-dependent: pull, breathe, kick, then glide. Rushing the sequence usually reduces efficiency.' },
  { id:'butterfly', category:'technique', keywordsAr:['فراشة','باترفلاي'], keywordsEn:['butterfly','fly stroke'], answerAr:'الفراشة مهارة متقدمة نسبيًا وتحتاج موجة جسم متصلة، ركلة دولفين متناسقة، وتوقيت واضح بين الذراعين والتنفس. الجودة أهم من عدد التكرارات.', answerEn:'Butterfly is relatively advanced and depends on connected body rhythm, coordinated dolphin kick, and clear timing between the arms and breathing. Quality matters more than repetition count.' },
  { id:'kick-efficiency', category:'technique', keywordsAr:['ركلة','رجلين','كيك'], keywordsEn:['kick','kicking','legs'], answerAr:'الركلة الفعالة تكون من الورك مع مرونة في الركبة والكاحل، وليس من ثني الركبة بقوة فقط. الرش الكبير لا يعني دائمًا دفعًا أفضل.', answerEn:'An efficient kick starts from the hip with relaxed knee and ankle action, not from aggressively bending the knees. Bigger splash does not always mean better propulsion.' },
  { id:'body-position', category:'technique', keywordsAr:['وضع الجسم','الجسم بيغرق','رجلي بتنزل'], keywordsEn:['body position','legs sink','hips sink'], answerAr:'وضع الجسم يتحسن عندما يكون الرأس هادئًا والجذع ثابتًا والتنفس منظمًا. رفع الرأس كثيرًا يدفع الحوض والرجلين لأسفل.', answerEn:'Body position improves when the head stays quiet, the core is controlled, and breathing is organized. Lifting the head too much tends to push the hips and legs down.' },
  { id:'stroke-efficiency', category:'technique', keywordsAr:['كفاءة','اقل مجهود','اتعب بسرعة'], keywordsEn:['efficiency','less effort','tire quickly'], answerAr:'الكفاءة تأتي من تقليل مقاومة الماء وتحسين التوقيت قبل محاولة زيادة القوة. سباحة أسرع لا تعني دائمًا تحريك الذراعين أسرع.', answerEn:'Efficiency comes from reducing drag and improving timing before adding more force. Swimming faster does not always mean moving the arms faster.' },
  { id:'turns-and-walls', category:'technique', keywordsAr:['لفة','الحائط','دوران','قلبة'], keywordsEn:['turn','wall','flip turn','push off'], answerAr:'التعامل الجيد مع الحائط يشمل الاقتراب المتزن، دوران مناسب للمستوى، دفع قوي في خط انسيابي، ثم عودة تدريجية للسباحة.', answerEn:'Good wall skills include a controlled approach, a turn appropriate to the swimmer level, a strong streamlined push-off, then a smooth return to swimming.' },
  { id:'progress-path', category:'progress', core:true, keywordsAr:['اتطور','تقدم','مراحل','مسار'], keywordsEn:['progress','improve','stages','path'], answerAr:'التقدم في السباحة عادة يبنى من الثقة والتحكم في الماء إلى التقنية، ثم الاتساق والتحمل والسرعة. تقييم التقدم يكون بجودة الحركة والاستقلال والثبات، وليس بالسرعة فقط.', answerEn:'Swimming progress usually builds from water confidence and control into technique, then consistency, endurance, and speed. Progress is measured by movement quality, independence, and repeatability, not speed alone.' },
  { id:'plateau', category:'progress', keywordsAr:['مش بتطور','ثابت','واقف مكاني','بلاتو'], keywordsEn:['plateau','not improving','stuck','no progress'], answerAr:'فترات الثبات طبيعية. الحل غالبًا يكون بتحديد مهارة واحدة قابلة للقياس، تقليل التعقيد، الحصول على ملاحظات، ثم تكرارها بجودة بدل تغيير كل شيء مرة واحدة.', answerEn:'Plateaus are normal. A useful response is to isolate one measurable skill, simplify the task, get feedback, and repeat it with quality instead of changing everything at once.' },
  { id:'practice-frequency', category:'progress', keywordsAr:['اتمرن كام مرة','عدد المرات','تكرار التدريب'], keywordsEn:['how often practice','frequency','times per week'], answerAr:'عدد الحصص المناسب يختلف حسب العمر والهدف والقدرة على الاستشفاء والجدول. المهم هو الانتظام وجودة التدريب؛ المواعيد الفعلية للأكاديمية تحتاج تأكيد الإدارة.', answerEn:'The right practice frequency varies with age, goals, recovery, and schedule. Consistency and quality matter most; the academy actual timetable needs management confirmation.' },
  { id:'goal-setting', category:'progress', keywordsAr:['هدفي','هدف','عايز اوصل'], keywordsEn:['goal','target','want to achieve'], answerAr:'أفضل هدف تدريبي يكون محددًا وقابلًا للملاحظة، مثل تحسين التنفس لمسافة قصيرة أو الحفاظ على وضع جسم أفضل، ثم الانتقال لهدف أصعب بعد ثبات المهارة.', answerEn:'A useful swimming goal is specific and observable, such as improving breathing over a short distance or holding a better body line, then progressing after the skill becomes consistent.' },
  { id:'children-learning', category:'parents', keywordsAr:['طفل','اطفال','ابني','بنتي'], keywordsEn:['child','children','kid','my son','my daughter'], answerAr:'تعلم الأطفال يكون أفضل عندما تكون الجلسة آمنة وإيجابية ومناسبة لقدرتهم على التركيز. الثقة والمهارات الأساسية تسبق الضغط على السرعة أو المسافات الطويلة.', answerEn:'Children learn best when sessions feel safe, positive, and appropriate to their attention span. Confidence and fundamentals come before pressure for speed or long distances.' },
  { id:'parent-support', category:'parents', keywordsAr:['ولي الامر','الاهل','اشجع ابني','اخلي طفلي يتعلم'], keywordsEn:['parent','support my child','help my kid'], answerAr:'أفضل دعم من ولي الأمر هو الهدوء والتشجيع وعدم مقارنة الطفل بغيره، مع الاهتمام بالانتظام والنوم والتجهيز للحصة أكثر من الضغط على النتيجة.', answerEn:'The best parent support is calm encouragement without comparing the child to others, while prioritizing consistency, sleep, and lesson preparation over pressure for results.' },
  { id:'child-fear', category:'parents', keywordsAr:['طفلي خايف','ابني خايف','بنتي خايفة'], keywordsEn:['child afraid','kid scared','my child fears water'], answerAr:'مع الطفل الخائف من الماء لا يُنصح بالإجبار أو المفاجأة. التدرج والاختيارات الصغيرة والنجاحات القصيرة تساعد على بناء الثقة بشكل أكثر استدامة.', answerEn:'For a child who fears water, forcing or surprising them is not a good approach. Gradual exposure, small choices, and short successes can build more durable confidence.' },
  { id:'adult-beginner', category:'adults', keywordsAr:['كبير','بالغ','عمري','اتعلم وانا كبير'], keywordsEn:['adult beginner','too old','learn as adult','my age'], answerAr:'تعلم السباحة للكبار ممكن، والبداية لا تحتاج خبرة سابقة. التدرج في التنفس والطفو ووضع الجسم يساعد على بناء أساس آمن قبل التركيز على السرعة.', answerEn:'Adults can learn to swim without prior experience. Gradual work on breathing, floating, and body position builds a safer foundation before focusing on speed.' },
  { id:'adult-fitness', category:'adults', keywordsAr:['لياقة','تخسيس','كارديو','رياضة'], keywordsEn:['fitness','cardio','exercise','weight loss'], answerAr:'السباحة يمكن أن تكون نشاطًا ممتازًا للياقة العامة لأنها تشغل مجموعات عضلية متعددة وتسمح بتدرج الشدة. أي هدف صحي أو علاجي محدد يحتاج توجيهًا طبيًا مناسبًا عند الحاجة.', answerEn:'Swimming can be excellent general fitness because it uses many muscle groups and allows intensity to scale. Specific medical or therapeutic goals should involve appropriate clinical guidance when needed.' },
  { id:'what-to-bring', category:'preparation', core:true, keywordsAr:['اجيب ايه','احضر ايه','شنطة','مستلزمات'], keywordsEn:['what to bring','pack','bag','equipment'], answerAr:'لجلسة سباحة عامة جهّز مايوه مناسب، منشفة، نظارة سباحة إن كانت مريحة لك، غطاء شعر عند الحاجة، مياه للشرب، وملابس جافة بعد التدريب.', answerEn:'For a general swim session, bring suitable swimwear, a towel, goggles if comfortable, a swim cap when useful, drinking water, and dry clothes for afterward.' },
  { id:'goggles', category:'preparation', keywordsAr:['نظارة','جوجلز','نضارة سباحة'], keywordsEn:['goggles','swim goggles'], answerAr:'النظارة الجيدة ينبغي أن تكون مريحة وتغلق حول العين بدون ضغط مبالغ. المقاس المناسب أهم من اختيار أغلى موديل.', answerEn:'Good goggles should feel comfortable and seal around the eyes without excessive pressure. Proper fit matters more than choosing the most expensive model.' },
  { id:'swim-cap', category:'preparation', keywordsAr:['كاب','غطاء الشعر','بونيه'], keywordsEn:['swim cap','cap'], answerAr:'غطاء السباحة يساعد على تثبيت الشعر وتقليل دخوله للوجه، وقد يكون مطلوبًا حسب سياسة المسبح. سياسة الموقع الفعلية تحتاج تأكيد الإدارة.', answerEn:'A swim cap helps keep hair controlled and away from the face, and some pools may require one. The actual venue policy needs management confirmation.' },
  { id:'hydration', category:'preparation', keywordsAr:['مياه','اشرب','ترطيب'], keywordsEn:['water','drink','hydration'], answerAr:'حتى في الماء يفقد الجسم سوائل، لذلك من المفيد الوصول مرطبًا وشرب الماء حسب الحاجة قبل وبعد التدريب.', answerEn:'You still lose fluid while swimming, so arriving hydrated and drinking water as needed before and after training is useful.' },
  { id:'arrival-prep', category:'preparation', keywordsAr:['اوصل امتى','قبل الحصة','استعداد'], keywordsEn:['arrive','before lesson','prepare'], answerAr:'بشكل عام من المفيد الوصول بوقت كافٍ لتغيير الملابس والاستعداد بهدوء بدل الدخول للحصة وأنت مستعجل. وقت الوصول المطلوب فعليًا يعتمد على الموقع وجدول الأكاديمية.', answerEn:'In general, arrive with enough time to change and settle in rather than rushing into the lesson. The exact arrival requirement depends on the venue and academy schedule.' },
  { id:'warmup', category:'fitness', keywordsAr:['احماء','تسخين','وارم اب'], keywordsEn:['warm up','warmup'], answerAr:'الإحماء الهادئ قبل الجهد يساعد الجسم على الانتقال تدريجيًا للعمل. يمكن أن يبدأ بحركة مفاصل بسيطة ثم سباحة سهلة قبل المجموعات الأصعب.', answerEn:'A gentle warm-up helps the body transition into harder work. It can begin with simple mobility and easy swimming before more demanding sets.' },
  { id:'endurance', category:'fitness', keywordsAr:['تحمل','نفس طويل','مسافة'], keywordsEn:['endurance','stamina','distance'], answerAr:'بناء التحمل يعتمد على الاستمرارية والإيقاع وتقنية اقتصادية أكثر من السباحة بأقصى سرعة من البداية. زد الحمل تدريجيًا مع الحفاظ على جودة الحركة.', answerEn:'Building endurance depends on consistency, pacing, and economical technique more than going all-out from the start. Increase load gradually while protecting movement quality.' },
  { id:'speed', category:'fitness', keywordsAr:['سرعة','اسرع','سريع'], keywordsEn:['speed','faster','sprint'], answerAr:'تحسين السرعة يبدأ غالبًا من انسيابية أفضل وتوقيت أقوى ثم إضافة القوة والسرعة. زيادة الجهد فوق تقنية غير مستقرة قد تزيد التعب أكثر من السرعة.', answerEn:'Speed often improves first through better streamlining and timing, then through added power. More effort on unstable technique can increase fatigue more than speed.' },
  { id:'recovery', category:'fitness', keywordsAr:['استشفاء','راحة','تعب','ارهاق'], keywordsEn:['recovery','rest','fatigue','tired'], answerAr:'الاستشفاء جزء من التدريب: نوم جيد، سوائل كافية، تغذية مناسبة، وأيام أخف عند الحاجة. الألم غير المعتاد أو المستمر يستحق تقييمًا متخصصًا.', answerEn:'Recovery is part of training: good sleep, hydration, appropriate nutrition, and lighter days when needed. Unusual or persistent pain deserves professional assessment.' },
  { id:'water-safety', category:'safety', core:true, keywordsAr:['سلامة','امان','غرق'], keywordsEn:['safety','safe','drowning','water safety'], answerAr:'السلامة في الماء أولوية: اتبع تعليمات المنقذ أو المدرب، لا تدخل عمقًا غير مناسب لقدرتك، ولا تعتمد على مهارة السباحة وحدها بدل الإشراف المناسب.', answerEn:'Water safety comes first: follow lifeguard or instructor directions, avoid depths beyond your ability, and never treat swimming skill as a substitute for appropriate supervision.' },
  { id:'never-swim-alone', category:'safety', keywordsAr:['لوحدي','اسبح وحدي','بدون مراقبة'], keywordsEn:['swim alone','alone','unsupervised'], answerAr:'لا يُنصح بالسباحة منفردًا في بيئة غير مراقبة، خصوصًا للمبتدئين والأطفال. وجود إشراف مناسب وخطة طوارئ جزء أساسي من السلامة.', answerEn:'Swimming alone in an unsupervised setting is not recommended, especially for beginners and children. Appropriate supervision and emergency readiness are core safety measures.' },
  { id:'pool-entry', category:'safety', keywordsAr:['انزل الميه','دخول المسبح','اقفز'], keywordsEn:['enter pool','jump in','pool entry'], answerAr:'استخدم طريقة دخول مناسبة لعمق المكان ومستواك واتبع تعليمات الموقع. القفز أو الغوص يحتاجان عمقًا ومهارة وإشرافًا مناسبين.', answerEn:'Use an entry method appropriate to the water depth and your skill, and follow venue rules. Jumping or diving requires suitable depth, skill, and supervision.' },
  { id:'pool-hygiene', category:'safety', keywordsAr:['نظافة','استحمام','كلور','هايجين'], keywordsEn:['hygiene','shower','chlorine','pool hygiene'], answerAr:'الاستحمام قبل السباحة واتباع تعليمات النظافة بالمسبح يساعدان في الحفاظ على بيئة أفضل للجميع. متطلبات الموقع المحددة تختلف من مسبح لآخر.', answerEn:'Showering before swimming and following pool hygiene rules helps maintain a better environment for everyone. Exact venue requirements vary by pool.' },
  { id:'illness', category:'safety', keywordsAr:['مريض','برد','حرارة','تعبان'], keywordsEn:['sick','ill','fever','unwell'], answerAr:'إذا كنت مريضًا أو لديك حرارة أو أعراض تؤثر على الأمان في الماء، فالأفضل تجنب التدريب حتى تكون حالتك مناسبة. للحالات الطبية المحددة استشر مختصًا.', answerEn:'If you are unwell, feverish, or have symptoms that affect water safety, it is better to avoid training until you are fit to participate. Specific medical conditions should be discussed with a clinician.' },
  { id:'injury', category:'safety', keywordsAr:['اصابة','كتف','ركبة','الم'], keywordsEn:['injury','shoulder pain','knee pain','pain'], answerAr:'الألم أو الإصابة ليست شيئًا يُفترض التدريب خلالها بلا تقييم. خفف أو أوقف النشاط المسبب للألم واطلب تقييمًا مناسبًا إذا استمر أو كان شديدًا.', answerEn:'Pain or injury should not simply be trained through without assessment. Reduce or stop the aggravating activity and seek appropriate evaluation if symptoms persist or are significant.' },
  { id:'lesson-expectations', category:'starting', keywordsAr:['الحصة بتكون ازاي','ماذا يحدث في الحصة','شكل التدريب'], keywordsEn:['what happens in a lesson','lesson structure','what to expect'], answerAr:'جلسة تعليم سباحة جيدة عادة تجمع بين مراجعة سريعة، هدف مهاري واضح، تمارين متدرجة، تطبيق عملي، ثم ملاحظات بسيطة لما يلي. تفاصيل الأكاديمية الفعلية تختلف حسب المستوى والجدول.', answerEn:'A well-structured swim lesson often combines a quick review, a clear skill goal, progressive drills, practical application, and simple next-step feedback. The academy exact format varies by level and schedule.' },
  { id:'feedback', category:'progress', keywordsAr:['ملاحظات','تصحيح','فيدباك'], keywordsEn:['feedback','correction','coach feedback'], answerAr:'الملاحظة المفيدة تكون محددة وقابلة للتنفيذ، مثل تغيير وضع الرأس أو توقيت التنفس، بدل أوامر عامة كثيرة في نفس الوقت.', answerEn:'Useful feedback is specific and actionable, such as changing head position or breathing timing, rather than giving many broad corrections at once.' },
  { id:'consistency', category:'progress', keywordsAr:['انتظام','استمرار','مواظبة'], keywordsEn:['consistency','regular','keep practicing'], answerAr:'الانتظام عادة أهم من جلسة قوية متقطعة. التكرار المنتظم لمهارة واحدة بجودة يبني التعلم العصبي والثقة بشكل أفضل.', answerEn:'Consistency usually matters more than occasional intense sessions. Repeating one skill regularly with quality supports motor learning and confidence.' },
  { id:'confidence-vs-speed', category:'progress', keywordsAr:['ثقة ولا سرعة','سرعة قبل المهارة'], keywordsEn:['confidence vs speed','speed before skill'], answerAr:'خصوصًا للمبتدئ، الثقة والتحكم والتقنية تأتي قبل السرعة. السرعة تصبح أكثر فائدة عندما يستطيع السباح الحفاظ على شكل جيد تحت الجهد.', answerEn:'Especially for beginners, confidence, control, and technique come before speed. Speed becomes more useful once the swimmer can maintain good form under effort.' },
  { id:'whatsapp-handoff-policy', category:'communication', core:true, keywordsAr:['السعر','المواعيد','العنوان','الموقع','تجربة','سيدات','المدرب'], keywordsEn:['price','schedule','address','location','trial','ladies','coach'], answerAr:'الأسعار والمواعيد والموقع الدقيق وسياسة التجربة وتوفر حصص السيدات وبيانات المدرب التفصيلية غير مؤكدة في قاعدة البيانات العامة؛ يجب تأكيدها مباشرة مع إدارة الأكاديمية عبر واتساب.', answerEn:'Pricing, schedules, exact venue, trial policy, ladies-only availability, and detailed coach credentials are not confirmed in the public data and must be confirmed directly with academy management on WhatsApp.' },
];

function normalize(input: string): string {
  return input.toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F]/g, '').replace(/[^\p{L}\p{N}\s]/gu, ' ').replace(/\s+/g, ' ').trim();
}

export interface KnowledgeMatch {
  readonly article: KnowledgeArticle;
  readonly score: number;
}

export function searchAcademyKnowledge(query: string, locale: 'ar' | 'en', limit = 6): readonly KnowledgeMatch[] {
  const normalized = normalize(query);
  if (!normalized) {
    return ACADEMY_KNOWLEDGE.filter((article) => article.core).slice(0, limit).map((article) => ({ article, score: 1 }));
  }
  const tokens = new Set(normalized.split(' ').filter((token) => token.length > 1));
  const ranked = ACADEMY_KNOWLEDGE.map((article) => {
    const keywords = [...article.keywordsAr, ...article.keywordsEn].map(normalize);
    let score = article.core ? 0.15 : 0;
    for (const keyword of keywords) {
      if (!keyword) continue;
      if (normalized.includes(keyword)) score += keyword.includes(' ') ? 4 : 3;
      for (const token of keyword.split(' ')) if (tokens.has(token) && token.length > 2) score += 0.5;
    }
    return { article, score };
  }).filter((match) => match.score > 0.15).sort((a, b) => b.score - a.score || a.article.id.localeCompare(b.article.id));
  return ranked.slice(0, limit);
}

export function knowledgeText(article: KnowledgeArticle, locale: 'ar' | 'en'): string {
  return locale === 'ar' ? article.answerAr : article.answerEn;
}

export function bestKnowledgeAnswer(query: string, locale: 'ar' | 'en'): string | null {
  const [best] = searchAcademyKnowledge(query, locale, 1);
  return best && best.score >= 1 ? knowledgeText(best.article, locale) : null;
}

export function knowledgeContext(query: string, locale: 'ar' | 'en', limit = 7): string {
  return searchAcademyKnowledge(query, locale, limit).map(({ article }) => `- [${article.category}/${article.id}] ${knowledgeText(article, locale)}`).join('\n');
}

export const KNOWLEDGE_ARTICLE_COUNT = ACADEMY_KNOWLEDGE.length;
